# nazwa programu:
#PROG = wprawki0
#PROG = wprawki1
#PROG = wprawki2
#PROG = wprawki3
#PROG = wprawki4
#PROG = wprawki5
#PROG = wprawki6
#PROG = wprawki7
#PROG = wprawki8
PROG = wprawki9

# biblioteki:
LIBS = -lGL -lGLU -lglut -lm

$(PROG) : $(PROG).c
	gcc -Wall -std=c99 $(PROG).c -o $(PROG) $(LIBS)

usun :
	rm -f $(PROG) *~
